import type { Metadata } from "next";
import Link from "next/link";
import { contactWhatsApp } from "@/lib/content";
import { ArticleStructuredData } from "@/components/structured-data";
import { RelatedArticles } from "@/components/related-articles";

export const metadata: Metadata = {
  title: "Bara bala: you can't feel without believing",
  description: "You can't have an emotion without a thought. Change the belief and the emotion changes. Your mind lies near change.",
  alternates: {
    canonical: "/en/blog/bara-bala-you-cant-feel-without-believing",
  },
};

export default function ArticlePage() {
  return (
    <div className="min-h-screen" style={{ background: "var(--bg-main)", color: "var(--text-main)" }}>
      <ArticleStructuredData
        title="Bara bala: you can't feel without believing"
        description="You can't have an emotion without a thought. Change the belief and the emotion changes. Your mind lies near change."
        slug="bara-bala-you-cant-feel-without-believing"
        date="2026-10-06"
        tag="Process"
        lang="en"
      />
      <header className="sticky top-0 z-30" style={{ borderBottom: "1px solid var(--border-subtle)", background: "var(--bg-main)" }}>
        <div className="mx-auto flex max-w-[1100px] items-center justify-between px-8 py-5">
          <Link href="/en" className="leading-none">
            <div className="text-[17px] font-semibold tracking-[-0.01em]" style={{ color: "var(--text-main)" }}>Ferran Moreno</div>
            <div className="mt-[5px] text-[10px] uppercase tracking-[0.14em]" style={{ color: "var(--text-secondary)", opacity: 0.7 }}>
              BODYWORK · REGULATION · ENERGY
            </div>
          </Link>

          <Link href="/" className="text-[11px] uppercase tracking-[0.08em] transition hover:opacity-50 md:hidden" style={{ color: "var(--text-secondary)" }}>ES</Link>

          <nav className="hidden items-center gap-8 md:flex" style={{ color: "var(--text-secondary)" }}>
            <Link href="/en" className="text-[11px] uppercase tracking-[0.08em] transition hover:opacity-50">Home</Link>
            <Link href="/en/wall-of-trust" className="text-[11px] uppercase tracking-[0.08em] transition hover:opacity-50">Wall of trust</Link>
            <Link href="/en/my-story" className="text-[11px] uppercase tracking-[0.08em] transition hover:opacity-50">My story</Link>
            <Link href="/en/blog" className="text-[11px] uppercase tracking-[0.08em] transition hover:opacity-50">Blog</Link>
            <a href={contactWhatsApp} target="_blank" rel="noopener noreferrer" className="text-[11px] uppercase tracking-[0.08em] transition hover:opacity-50">Contact</a>
            <span style={{ color: "var(--border-subtle)" }}>|</span>
            <Link href="/" className="text-[11px] uppercase tracking-[0.08em] transition hover:opacity-50">ES</Link>
          </nav>
        </div>
      </header>

      <main className="mx-auto max-w-[700px] px-6 py-24">
        <Link href="/en/blog" className="text-[11px] uppercase tracking-[0.15em] mb-12 inline-block transition hover:opacity-50" style={{ color: "var(--text-secondary)" }}>
          &larr; Blog
        </Link>

        <article>
          <span className="text-[10px] uppercase tracking-[0.15em] mb-4 block" style={{ color: "var(--text-secondary)" }}>
            Process
          </span>

          <h1 className="text-3xl font-semibold tracking-tight mb-10 leading-[1.15] lg:text-4xl">
            Bara bala: you can&apos;t feel without believing
          </h1>

          <div className="space-y-6">
            <p className="text-[15px] leading-relaxed">
              Bara bala. Your brain is receiving that information right now. Bara bala. And it produces absolutely nothing. No emotion. No reaction. No internal movement. Because you have no thought or definition attached to those words.
            </p>

            <p className="text-[15px] leading-relaxed">
              Now think of something that worries you. Your body reacts instantly. Something contracts. Your breathing changes. Heart rate goes up. The difference between bara bala and your worry is one single thing: a belief.
            </p>

            <h2 className="text-xl font-semibold tracking-tight mt-12 mb-4">
              No thought, no emotion
            </h2>

            <p className="text-[15px] leading-relaxed">
              You cannot have an emotion without a prior thought. It&apos;s impossible. If I say a word that has no meaning for you, your brain produces zero emotional response. This means something enormous: the emotion you feel right now isn&apos;t generated by reality. It&apos;s generated by a belief about reality.
            </p>

            <p className="text-[15px] leading-relaxed">
              This isn&apos;t philosophy. It&apos;s mechanics. Your nervous system responds to what your mind interprets, not to what happens. Change the interpretation and the emotional response changes. Not immediately. Not without work. But it changes.
            </p>

            <h2 className="text-xl font-semibold tracking-tight mt-12 mb-4">
              The mind lies near change
            </h2>

            <p className="text-[15px] leading-relaxed">
              Here&apos;s where it gets interesting. When you&apos;re close to a real structural change &mdash; when something in your system is about to reorganize &mdash; the survival mind panics. And it manufactures lies that sound perfectly logical.
            </p>

            <p className="text-[15px] leading-relaxed">
              &ldquo;This isn&apos;t working.&rdquo; &ldquo;I&apos;m worse than before.&rdquo; &ldquo;I should quit.&rdquo; The lies are designed to be logical. That&apos;s the trap. If they were absurd you wouldn&apos;t believe them. But they sound reasonable, and that&apos;s why you buy them.
            </p>

            <h2 className="text-xl font-semibold tracking-tight mt-12 mb-4">
              Trust radiates from the inside out
            </h2>

            <p className="text-[15px] leading-relaxed">
              Trust isn&apos;t built by accumulating external evidence. It doesn&apos;t come from someone proving to you that it works. It radiates from the inside out. First you trust. Then you see. Not the other way around.
            </p>

            <p className="text-[15px] leading-relaxed font-medium">
              If bara bala produces nothing in you, you already have the proof. Your emotions are not reality. They are the story you tell yourself about it. Change the story and everything changes.
            </p>
          </div>

          <div className="mt-20 pt-12" style={{ borderTop: "1px solid var(--border-subtle)" }}>
            <p className="text-[15px] leading-relaxed mb-6" style={{ color: "var(--text-secondary)" }}>
              If you feel your emotions hijack you and you want to understand what beliefs sustain them, write me.
            </p>
            <a
              href={contactWhatsApp}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-block text-[11px] uppercase tracking-[0.15em] font-medium transition hover:opacity-50"
              style={{ color: "var(--text-main)" }}
            >
              Write me &rarr;
            </a>
          </div>

          <RelatedArticles slug="bara-bala-you-cant-feel-without-believing" lang="en" />
        </article>
      </main>
    </div>
  );
}
