import type { MetadataRoute } from "next";
import { siteUrl } from "@/lib/content";

const blogSlugsEs = [
  "20-anos-formandome-en-20-paises",
  "ansiedad-sin-causa",
  "bara-bala-no-puedes-sentir-sin-creer",
  "ceos-y-sistema-nervioso",
  "compensar-no-es-curar-v2",
  "contraccion-o-expansion",
  "cuando-entendi-que-la-tecnica-me-limitaba",
  "cuerpos-pidiendo-permiso-para-descansar",
  "do-no-harm",
  "el-alivio-no-es-expansion",
  "el-coste-fisiologico-de-sostener-presion",
  "el-cuerpo-cambia-cuando-deja-de-defenderse",
  "el-cuerpo-decide-antes-que-la-mente",
  "el-cuerpo-necesita-seguridad-no-control",
  "el-cuerpo-no-esta-roto-esta-compensando",
  "el-cuerpo-no-fue-disenado-siempre-disponible",
  "el-cuerpo-organiza-supervivencia",
  "el-cuerpo-recuerda-lo-que-la-mente-olvido",
  "el-cuerpo-sabe-antes-que-tu",
  "el-cuerpo-siempre-intenta-protegerte",
  "el-dia-que-deje-de-ser-pinocho-v2",
  "el-dolor-rara-vez-empieza-donde-duele",
  "el-freno-de-mano-del-cuerpo",
  "el-problema-no-es-el-estres",
  "el-sintoma-no-es-el-enemigo",
  "el-topo-mecanismo-mental",
  "intensidad-e-invasion-no-son-lo-mismo",
  "la-barista-que-lloro",
  "la-curandera-de-robleda",
  "la-diferencia-entre-reorganizar-y-reparar",
  "la-espalda-casi-nunca-es-el-problema",
  "la-fascia-real",
  "la-precision-siempre-gana-a-la-fuerza",
  "la-ram-del-sistema-nervioso",
  "la-regulacion-no-es-relajacion",
  "la-sombra-te-hace-olvidar",
  "la-tension-cambia-quien-crees-que-eres",
  "las-casetes-mentales",
  "las-personas-con-la-mochila",
  "lo-que-aprendi-en-kamalaya",
  "lo-que-aprendi-tocando-miles-de-cuerpos",
  "lo-que-tus-manos-pueden-leer",
  "los-ojos-del-campesino-v2",
  "manager-o-micromanager-de-tu-vida",
  "no-estan-cansadas-estan-compensando",
  "no-hay-nada-solo-fisico",
  "no-necesitas-entender-necesitas-estar-bien",
  "personas-en-defensa-desde-hace-decadas",
  "por-que-algunas-lesiones-nunca-se-curan",
  "por-que-trabajo-por-proceso",
  "que-esperar-en-tu-primera-sesion",
  "que-pasa-en-una-sesion",
  "rendimiento-sostenible",
  "rolfing-europa-vs-usa-v2",
  "rolfing-vs-fisioterapia-diferencia",
  "roncesvalles-morir-la-coruna-vivir-v2",
  "siempre-buscar-el-punto-de-origen",
  "siete-anos-de-dolor",
  "sostener-tu-luz",
  "todo-es-frecuencia",
  "trabajo-corporal-despues-del-embarazo",
  "trabajo-energetico-no-es-lo-que-piensas",
  "tu-cuerpo-no-necesita-mas-fuerza",
  "tu-respiracion-cambia-antes",
  "tu-sistema-nervioso-escucha-todo",
  "tu-sistema-nervioso-no-distingue-amenaza",
  "tus-organos-se-mueven",
  "viajes-jet-lag-deuda-nerviosa",
  "vivir-en-naranja"
];

const blogSlugsEn = [
  "20-years-training-across-20-countries",
  "always-find-the-point-of-origin",
  "anxiety-without-apparent-cause",
  "bara-bala-you-cant-feel-without-believing",
  "bodies-asking-permission-to-rest",
  "bodywork-after-pregnancy",
  "ceos-and-the-nervous-system",
  "compensating-isnt-healing",
  "contraction-or-expansion",
  "do-no-harm",
  "energy-work-isnt-what-you-think",
  "european-rolfing-vs-american",
  "everything-is-frequency",
  "hold-your-light",
  "intensity-and-invasion-arent-the-same",
  "living-in-amber",
  "manager-or-micromanager-of-your-life",
  "not-tired-compensating",
  "nothing-is-just-physical",
  "pain-rarely-starts-where-it-hurts",
  "people-in-defense-for-decades",
  "precision-always-beats-force",
  "regulation-isnt-relaxation",
  "relief-isnt-expansion",
  "rolfing-vs-physiotherapy-difference",
  "roncesvalles-to-die-coruna-to-live",
  "seven-years-of-pain",
  "sustainable-performance",
  "tension-changes-who-you-think-you-are",
  "the-back-is-almost-never-the-problem",
  "the-barista-who-cried",
  "the-body-always-tries-to-protect-you",
  "the-body-changes-when-it-stops-defending",
  "the-body-decides-before-the-mind",
  "the-body-knows-before-you-do",
  "the-body-needs-safety-not-control",
  "the-body-organizes-survival-before-comfort",
  "the-body-remembers-what-the-mind-forgot",
  "the-body-wasnt-designed-to-be-always-available",
  "the-bodys-handbrake",
  "the-day-i-stopped-being-pinocchio",
  "the-difference-between-reorganizing-and-repairing",
  "the-farmers-eyes",
  "the-healer-of-robleda",
  "the-mental-cassette-tapes",
  "the-mole-mental-mechanism",
  "the-people-with-the-sack",
  "the-physiological-cost-of-sustained-pressure",
  "the-problem-isnt-stress",
  "the-ram-of-your-nervous-system",
  "the-shadow-makes-you-forget",
  "the-symptom-isnt-the-enemy",
  "travel-jet-lag-nervous-debt",
  "what-i-learned-in-kamalaya",
  "what-i-learned-touching-thousands-of-bodies",
  "what-nobody-tells-you-about-fascia",
  "what-really-happens-in-a-session",
  "what-to-expect-first-session",
  "what-your-hands-can-read",
  "when-technique-becomes-the-limit",
  "why-i-work-by-process-not-single-sessions",
  "why-some-injuries-never-fully-heal",
  "you-dont-need-to-understand-you-need-to-be-well",
  "your-body-doesnt-need-more-force",
  "your-body-isnt-broken-its-compensating",
  "your-breathing-changes-first",
  "your-nervous-system-cant-tell-the-difference",
  "your-nervous-system-hears-everything",
  "your-organs-need-to-move"
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const pages: MetadataRoute.Sitemap = [
    { url: siteUrl, lastModified: now, changeFrequency: "monthly", priority: 1 },
    { url: `${siteUrl}/wall-of-trust`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/historia`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${siteUrl}/contacto`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/en`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${siteUrl}/en/wall-of-trust`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/en/my-story`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/en/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${siteUrl}/trabajo-corporal-online`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${siteUrl}/en/online-bodywork`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${siteUrl}/en/rolfing-berlin`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-new-york`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-london`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-tel-aviv`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-reykjavik`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-oslo`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-tokyo`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    // Zone pages ES
    { url: `${siteUrl}/rolfing-barcelona`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${siteUrl}/rolfing-girona`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-lleida`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-vic`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-manresa`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-berga`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-la-seu-urgell`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-osona`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-buenos-aires`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-ciudad-de-mexico`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-santiago-chile`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-bariloche`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
  ];

  for (const slug of blogSlugsEs) {
    pages.push({ url: `${siteUrl}/blog/${slug}`, lastModified: now, changeFrequency: "monthly", priority: 0.6 });
  }

  for (const slug of blogSlugsEn) {
    pages.push({ url: `${siteUrl}/en/blog/${slug}`, lastModified: now, changeFrequency: "monthly", priority: 0.6 });
  }

  return pages;
}
