import type { MetadataRoute } from "next";
import { siteUrl } from "@/lib/content";

const blogSlugsEs = [
  "por-que-tomas-malas-decisiones-cuando-estas-estresado",
  "dolor-cronico-sin-solucion-cuando-el-problema-no-es-donde-duele",
  "que-es-la-regulacion-del-sistema-nervioso",
  "rolfing-duele-la-verdad",
  "cuando-el-cuerpo-compensa-mas-tecnica-no-lo-soluciona",
  "no-necesitas-entender-necesitas-estar-bien",
  "que-esperar-en-tu-primera-sesion",
  "dolor-de-espalda-cronico-origen",
  "rolfing-vs-fisioterapia-diferencia",
  "que-pasa-en-una-sesion",
  "ansiedad-sin-causa-aparente",
  "trabajo-corporal-despues-del-embarazo",
  "el-topo-mecanismo-mental",
  "lesiones-deportivas-que-no-se-curan",
  "tu-cuerpo-no-esta-roto",
  "20-anos-formandome-en-20-paises",
  "trabajo-energetico-no-es-lo-que-piensas",
  "rolfing-europa-vs-usa",
  "diferencia-entre-intensidad-e-invasion",
  "por-que-trabajo-por-proceso",
  "compensar-no-es-curar",
  "por-que-los-ceos-necesitan-trabajo-corporal",
  "rendimiento-sostenible-cuerpo-como-infraestructura",
  "viajes-jet-lag-sistema-nervioso",
  "diez-anos-de-dolor-una-sesion",
  "los-ojos-del-campesino",
  "la-mujer-que-leia-la-espalda",
  "el-dia-que-deje-de-ser-pinocho",
  "roncesvalles-morir-la-coruna-vivir",
  "lo-que-nadie-te-cuenta-sobre-la-fascia",
  "tus-organos-necesitan-moverse",
  "lo-que-tus-manos-pueden-leer",
  "cuando-la-tecnica-te-limita",
  "la-ram-de-tu-sistema-nervioso",
  "sostener-tu-luz",
  "la-sombra-te-hace-olvidar",
  "las-casetes-mentales",
  "el-freno-de-mano-del-cuerpo",
  "manager-o-micromanager-de-tu-vida",
  "contraccion-o-expansion",
  "las-personas-con-la-mochila",
  "del-alivio-a-la-expansion",
  "que-te-diria-tu-yo-del-futuro",
  "buscar-el-punto-de-origen",
  "cuando-el-cuerpo-lleva-anos-cayendose",
  "la-barista-que-lloro",
  "no-hay-nada-solo-fisico",
  "bara-bala-no-puedes-sentir-sin-creer",
  "todo-es-frecuencia",
];

const blogSlugsEn = [
  "why-you-make-bad-decisions-when-stressed",
  "chronic-pain-when-the-problem-isnt-where-it-hurts",
  "what-is-nervous-system-regulation",
  "does-rolfing-hurt-the-truth",
  "when-your-body-compensates-more-technique-wont-fix-it",
  "you-dont-need-to-understand-you-need-to-be-well",
  "what-to-expect-first-session",
  "chronic-back-pain-origin",
  "rolfing-vs-physiotherapy-difference",
  "what-really-happens-in-a-session",
  "anxiety-without-apparent-cause",
  "bodywork-after-pregnancy",
  "the-mole-mental-mechanism",
  "sports-injuries-that-wont-heal",
  "your-body-isnt-broken",
  "20-years-training-across-20-countries",
  "energy-work-isnt-what-you-think",
  "european-rolfing-vs-american",
  "difference-between-intensity-and-invasion",
  "why-i-work-by-process-not-single-sessions",
  "compensating-isnt-healing",
  "why-ceos-need-bodywork",
  "sustainable-performance-body-as-infrastructure",
  "travel-jet-lag-nervous-system",
  "ten-years-of-pain-one-session",
  "the-farmers-eyes",
  "the-woman-who-read-spines-like-braille",
  "the-day-i-stopped-being-pinocchio",
  "roncesvalles-to-die-coruna-to-live",
  "what-nobody-tells-you-about-fascia",
  "your-organs-need-to-move",
  "what-your-hands-can-read",
  "when-technique-becomes-the-limit",
  "the-ram-of-your-nervous-system",
  "hold-your-light",
  "the-shadow-makes-you-forget",
  "the-mental-cassette-tapes",
  "the-bodys-handbrake",
  "manager-or-micromanager-of-your-life",
  "contraction-or-expansion",
  "the-people-with-the-sack",
  "from-relief-to-expansion",
  "what-would-your-future-self-tell-you",
  "always-find-the-point-of-origin",
  "when-the-body-has-been-falling-for-years",
  "the-barista-who-cried",
  "nothing-is-just-physical",
  "bara-bala-you-cant-feel-without-believing",
  "everything-is-frequency",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  const pages: MetadataRoute.Sitemap = [
    { url: siteUrl, lastModified: now, changeFrequency: "monthly", priority: 1 },
    { url: `${siteUrl}/wall-of-trust`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/historia`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${siteUrl}/en`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${siteUrl}/en/wall-of-trust`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/en/my-story`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/en/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    // Zone pages (local SEO)
    { url: `${siteUrl}/rolfing-barcelona`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${siteUrl}/rolfing-girona`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-lleida`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-vic`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-manresa`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-berga`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-la-seu-urgell`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-osona`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
  ];

  for (const slug of blogSlugsEs) {
    pages.push({ url: `${siteUrl}/blog/${slug}`, lastModified: now, changeFrequency: "monthly", priority: 0.6 });
  }

  for (const slug of blogSlugsEn) {
    pages.push({ url: `${siteUrl}/en/blog/${slug}`, lastModified: now, changeFrequency: "monthly", priority: 0.6 });
  }

  return pages;
}
