import type { MetadataRoute } from "next";
import { siteUrl } from "@/lib/content";

export const revalidate = 86400;

const blogPostsEs: { slug: string; date: string }[] = [
  { slug: "20-anos-formandome-en-20-paises", date: "2026-03-24" },
  { slug: "ansiedad-sin-causa", date: "2026-07-03" },
  { slug: "bara-bala-no-puedes-sentir-sin-creer", date: "2026-02-07" },
  { slug: "ceos-y-sistema-nervioso", date: "2026-09-15" },
  { slug: "compensar-no-es-curar-v2", date: "2026-05-22" },
  { slug: "como-se-define-el-precio-de-una-intervencion", date: "2026-05-27" },
  { slug: "no-hace-falta-estar-en-crisis-para-venir", date: "2026-05-28" },
  { slug: "contraccion-o-expansion", date: "2026-02-11" },
  { slug: "cuando-entendi-que-la-tecnica-me-limitaba", date: "2026-09-11" },
  { slug: "cuerpos-pidiendo-permiso-para-descansar", date: "2026-10-06" },
  { slug: "do-no-harm", date: "2026-06-05" },
  { slug: "el-alivio-no-es-expansion", date: "2026-07-14" },
  { slug: "el-coste-fisiologico-de-sostener-presion", date: "2026-09-18" },
  { slug: "el-cuerpo-cambia-cuando-deja-de-defenderse", date: "2026-08-07" },
  { slug: "el-cuerpo-decide-antes-que-la-mente", date: "2026-05-26" },
  { slug: "el-cuerpo-necesita-seguridad-no-control", date: "2026-07-07" },
  { slug: "el-cuerpo-no-esta-roto-esta-compensando", date: "2026-05-15" },
  { slug: "el-cuerpo-no-fue-disenado-siempre-disponible", date: "2026-09-29" },
  { slug: "el-cuerpo-organiza-supervivencia", date: "2026-05-29" },
  { slug: "el-cuerpo-recuerda-lo-que-la-mente-olvido", date: "2026-06-26" },
  { slug: "el-cuerpo-sabe-antes-que-tu", date: "2026-10-20" },
  { slug: "el-cuerpo-siempre-intenta-protegerte", date: "2026-10-13" },
  { slug: "el-dia-que-deje-de-ser-pinocho-v2", date: "2026-08-21" },
  { slug: "el-dolor-rara-vez-empieza-donde-duele", date: "2026-07-31" },
  { slug: "el-freno-de-mano-del-cuerpo", date: "2026-03-08" },
  { slug: "el-problema-no-es-el-estres", date: "2026-06-12" },
  { slug: "el-sintoma-no-es-el-enemigo", date: "2026-10-09" },
  { slug: "el-topo-mecanismo-mental", date: "2026-02-19" },
  { slug: "intensidad-e-invasion-no-son-lo-mismo", date: "2026-07-21" },
  { slug: "la-barista-que-lloro", date: "2026-01-30" },
  { slug: "la-curandera-de-robleda", date: "2026-08-28" },
  { slug: "la-diferencia-entre-reorganizar-y-reparar", date: "2026-06-09" },
  { slug: "la-espalda-casi-nunca-es-el-problema", date: "2026-08-14" },
  { slug: "la-fascia-real", date: "2026-07-24" },
  { slug: "la-precision-siempre-gana-a-la-fuerza", date: "2026-06-02" },
  { slug: "la-ram-del-sistema-nervioso", date: "2026-06-30" },
  { slug: "la-regulacion-no-es-relajacion", date: "2026-07-17" },
  { slug: "la-sombra-te-hace-olvidar", date: "2026-02-15" },
  { slug: "la-tension-cambia-quien-crees-que-eres", date: "2026-10-27" },
  { slug: "las-casetes-mentales", date: "2026-02-23" },
  { slug: "las-personas-con-la-mochila", date: "2026-01-26" },
  { slug: "lo-que-aprendi-en-kamalaya", date: "2026-09-04" },
  { slug: "lo-que-aprendi-tocando-miles-de-cuerpos", date: "2026-09-08" },
  { slug: "lo-que-tus-manos-pueden-leer", date: "2026-03-28" },
  { slug: "los-ojos-del-campesino-v2", date: "2026-08-25" },
  { slug: "manager-o-micromanager-de-tu-vida", date: "2026-02-03" },
  { slug: "no-estan-cansadas-estan-compensando", date: "2026-06-19" },
  { slug: "no-hay-nada-solo-fisico", date: "2026-03-12" },
  { slug: "no-necesitas-entender-necesitas-estar-bien", date: "2026-02-27" },
  { slug: "personas-en-defensa-desde-hace-decadas", date: "2026-10-23" },
  { slug: "por-que-algunas-lesiones-nunca-se-curan", date: "2026-08-04" },
  { slug: "por-que-trabajo-por-proceso", date: "2026-04-29" },
  { slug: "que-esperar-en-tu-primera-sesion", date: "2026-04-25" },
  { slug: "que-pasa-en-una-sesion", date: "2026-04-22" },
  { slug: "rendimiento-sostenible", date: "2026-09-22" },
  { slug: "rolfing-europa-vs-usa-v2", date: "2026-08-11" },
  { slug: "rolfing-vs-fisioterapia-diferencia", date: "2026-04-18" },
  { slug: "roncesvalles-morir-la-coruna-vivir-v2", date: "2026-09-01" },
  { slug: "siempre-buscar-el-punto-de-origen", date: "2026-05-19" },
  { slug: "siete-anos-de-dolor", date: "2026-08-18" },
  { slug: "sostener-tu-luz", date: "2026-01-22" },
  { slug: "todo-es-frecuencia", date: "2026-03-20" },
  { slug: "trabajo-corporal-despues-del-embarazo", date: "2026-04-15" },
  { slug: "trabajo-energetico-no-es-lo-que-piensas", date: "2026-03-16" },
  { slug: "tu-cuerpo-no-necesita-mas-fuerza", date: "2026-10-02" },
  { slug: "tu-respiracion-cambia-antes", date: "2026-07-10" },
  { slug: "tu-sistema-nervioso-escucha-todo", date: "2026-10-16" },
  { slug: "tu-sistema-nervioso-no-distingue-amenaza", date: "2026-06-16" },
  { slug: "tus-organos-se-mueven", date: "2026-07-28" },
  { slug: "viajes-jet-lag-deuda-nerviosa", date: "2026-09-25" },
  { slug: "vivir-en-naranja", date: "2026-06-23" }
];

const blogPostsEn: { slug: string; date: string }[] = [
  { slug: "20-years-training-across-20-countries", date: "2026-03-24" },
  { slug: "always-find-the-point-of-origin", date: "2026-05-19" },
  { slug: "anxiety-without-apparent-cause", date: "2026-07-03" },
  { slug: "bara-bala-you-cant-feel-without-believing", date: "2026-02-07" },
  { slug: "bodies-asking-permission-to-rest", date: "2026-10-06" },
  { slug: "bodywork-after-pregnancy", date: "2026-04-15" },
  { slug: "ceos-and-the-nervous-system", date: "2026-09-15" },
  { slug: "compensating-isnt-healing", date: "2026-05-22" },
  { slug: "contraction-or-expansion", date: "2026-02-11" },
  { slug: "do-no-harm", date: "2026-06-05" },
  { slug: "energy-work-isnt-what-you-think", date: "2026-03-16" },
  { slug: "european-rolfing-vs-american", date: "2026-08-11" },
  { slug: "everything-is-frequency", date: "2026-03-20" },
  { slug: "hold-your-light", date: "2026-01-22" },
  { slug: "intensity-and-invasion-arent-the-same", date: "2026-07-21" },
  { slug: "living-in-amber", date: "2026-06-23" },
  { slug: "manager-or-micromanager-of-your-life", date: "2026-02-03" },
  { slug: "not-tired-compensating", date: "2026-06-19" },
  { slug: "nothing-is-just-physical", date: "2026-03-12" },
  { slug: "pain-rarely-starts-where-it-hurts", date: "2026-07-31" },
  { slug: "people-in-defense-for-decades", date: "2026-10-23" },
  { slug: "you-dont-have-to-be-in-crisis-to-come", date: "2026-05-28" },
  { slug: "precision-always-beats-force", date: "2026-06-02" },
  { slug: "regulation-isnt-relaxation", date: "2026-07-17" },
  { slug: "relief-isnt-expansion", date: "2026-07-14" },
  { slug: "rolfing-vs-physiotherapy-difference", date: "2026-04-18" },
  { slug: "roncesvalles-to-die-coruna-to-live", date: "2026-09-01" },
  { slug: "seven-years-of-pain", date: "2026-08-18" },
  { slug: "sustainable-performance", date: "2026-09-22" },
  { slug: "tension-changes-who-you-think-you-are", date: "2026-10-27" },
  { slug: "the-back-is-almost-never-the-problem", date: "2026-08-14" },
  { slug: "the-barista-who-cried", date: "2026-01-30" },
  { slug: "the-body-always-tries-to-protect-you", date: "2026-10-13" },
  { slug: "the-body-changes-when-it-stops-defending", date: "2026-08-07" },
  { slug: "the-body-decides-before-the-mind", date: "2026-05-26" },
  { slug: "the-body-knows-before-you-do", date: "2026-10-20" },
  { slug: "the-body-needs-safety-not-control", date: "2026-07-07" },
  { slug: "the-body-organizes-survival-before-comfort", date: "2026-05-29" },
  { slug: "the-body-remembers-what-the-mind-forgot", date: "2026-06-26" },
  { slug: "the-body-wasnt-designed-to-be-always-available", date: "2026-09-29" },
  { slug: "the-bodys-handbrake", date: "2026-03-08" },
  { slug: "the-day-i-stopped-being-pinocchio", date: "2026-08-21" },
  { slug: "the-difference-between-reorganizing-and-repairing", date: "2026-06-09" },
  { slug: "the-farmers-eyes", date: "2026-08-25" },
  { slug: "the-healer-of-robleda", date: "2026-08-28" },
  { slug: "the-mental-cassette-tapes", date: "2026-02-23" },
  { slug: "the-mole-mental-mechanism", date: "2026-02-19" },
  { slug: "the-people-with-the-sack", date: "2026-01-26" },
  { slug: "the-physiological-cost-of-sustained-pressure", date: "2026-09-18" },
  { slug: "the-problem-isnt-stress", date: "2026-06-12" },
  { slug: "the-ram-of-your-nervous-system", date: "2026-06-30" },
  { slug: "the-shadow-makes-you-forget", date: "2026-02-15" },
  { slug: "the-symptom-isnt-the-enemy", date: "2026-10-09" },
  { slug: "travel-jet-lag-nervous-debt", date: "2026-09-25" },
  { slug: "what-i-learned-in-kamalaya", date: "2026-09-04" },
  { slug: "what-i-learned-touching-thousands-of-bodies", date: "2026-09-08" },
  { slug: "what-nobody-tells-you-about-fascia", date: "2026-07-24" },
  { slug: "what-really-happens-in-a-session", date: "2026-04-22" },
  { slug: "what-to-expect-first-session", date: "2026-04-25" },
  { slug: "what-your-hands-can-read", date: "2026-03-28" },
  { slug: "when-technique-becomes-the-limit", date: "2026-09-11" },
  { slug: "why-i-work-by-process-not-single-sessions", date: "2026-04-29" },
  { slug: "what-defines-the-price-of-an-intervention", date: "2026-05-27" },
  { slug: "why-some-injuries-never-fully-heal", date: "2026-08-04" },
  { slug: "you-dont-need-to-understand-you-need-to-be-well", date: "2026-02-27" },
  { slug: "your-body-doesnt-need-more-force", date: "2026-10-02" },
  { slug: "your-body-isnt-broken-its-compensating", date: "2026-05-15" },
  { slug: "your-breathing-changes-first", date: "2026-07-10" },
  { slug: "your-nervous-system-cant-tell-the-difference", date: "2026-06-16" },
  { slug: "your-nervous-system-hears-everything", date: "2026-10-16" },
  { slug: "your-organs-need-to-move", date: "2026-07-28" }
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  const today = now.toISOString().split("T")[0];

  const pages: MetadataRoute.Sitemap = [
    { url: siteUrl, lastModified: now, changeFrequency: "monthly", priority: 1 },
    { url: `${siteUrl}/wall-of-trust`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/historia`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${siteUrl}/contacto`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/monica`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${siteUrl}/en`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${siteUrl}/en/contact`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/en/wall-of-trust`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/en/my-story`, lastModified: now, changeFrequency: "monthly", priority: 0.7 },
    { url: `${siteUrl}/en/blog`, lastModified: now, changeFrequency: "weekly", priority: 0.8 },
    { url: `${siteUrl}/en/monica`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${siteUrl}/trabajo-corporal-online`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${siteUrl}/en/online-bodywork`, lastModified: now, changeFrequency: "monthly", priority: 0.5 },
    { url: `${siteUrl}/en/rolfing-berlin`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-new-york`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-london`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-tel-aviv`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-reykjavik`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-oslo`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/en/rolfing-tokyo`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    // Zone pages ES
    { url: `${siteUrl}/rolfing-barcelona`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${siteUrl}/rolfing-girona`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-lleida`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-vic`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-manresa`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-berga`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-la-seu-urgell`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-osona`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-buenos-aires`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-ciudad-de-mexico`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-santiago-chile`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${siteUrl}/rolfing-bariloche`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
  ];

  for (const post of blogPostsEs) {
    if (post.date <= today) {
      pages.push({ url: `${siteUrl}/blog/${post.slug}`, lastModified: new Date(post.date), changeFrequency: "monthly", priority: 0.6 });
    }
  }

  for (const post of blogPostsEn) {
    if (post.date <= today) {
      pages.push({ url: `${siteUrl}/en/blog/${post.slug}`, lastModified: new Date(post.date), changeFrequency: "monthly", priority: 0.6 });
    }
  }

  return pages;
}
